version: '3'
services:
  server:
    restart: always
    build: ./server
    ports:
      - "4000:4000"
    links:
      - mongodb
    volumes:
      - ./server:/app
  client:
    build: ./client
    volumes:
      - './client:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
  mongodb:
    image: 'mongo'
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db

